In [ ]:
import logging
import os
import pickle
import random
import sys
from os.path import join

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import xgboost as xgb
from rdkit import Chem
from rdkit.Chem import AllChem
from sklearn.metrics import matthews_corrcoef, roc_auc_score
from sklearn.model_selection import KFold

sys.path.append("./additional_code")
# from data_preprocessing import *
CURRENT_DIR = os.getcwd()
print(CURRENT_DIR)
our_data = CURRENT_DIR + "/../data/our_data/"

/home/hanxd/Repositories/ESP/our_codes

In [ ]:
df_enzymedata = pd.read_csv(
    our_data + "Digitalis_leaf_PF00067_Merge98_Sort_Express.csv"
)
df_enzymedata

          enzyme                                           Sequence
0    Droo_175168  VLLALPVILILLYLKQKSSGKRRRQPPGPSGLPFIGNLHQFDGIYP...
1    Dcom_195433  MRANTAEKWITERAKRYGPVSKLSLFGNATVFIYGQSANKFLFADN...
2    Dcom_249831  MTLKFGMINIVVASSTEMAKEILQKKDQTFLGRPVPDAIRGEKGYE...
3    Dcom_272966  MGLPFFGEMLAFLWYFKVIRRPDDYINVKRRKYGDGEGLYRTHLFG...
4    Dcom_061020  MTHVTLSNLAKIHGPVMSFKLGTQLLIVGSSSAAAEEILKTNDRIL...
..           ...                                                ...
290  Droo_046339  MAHAVSSCVSYSHLLVNRQNELPSSRSPSSPVTHFSNCKRKGFSVR...
291  Dcom_143281  MASASSWLHKSFHDSLLCFFILSLTIMFLILFIFHLLRVRIWCNCE...
292  Droo_148538  MPNYQFMALISHFTTTPPPPTHDPFMSYSYFSNYLHSIIMASPNHS...
293  Droo_006827  MASSLSLLQLSPQILQTRGQRNRLSNVKSNGTGRDARRFRCSSSLN...
294  Dcom_165338  MSWWWAGAIGAAKKKLEEDDAPPKHSSVALIVGVTGIIGNSLAEIL...

[295 rows x 2 columns]

In [ ]:
data = {
    "substrate1": ["3β-hydroxy-5β-pregnane-20-one"],
    "substrate2": ["5β-pregnane-3β,14β-diol-20-one"],
    "substrate3": ["digitoxigenin"],
}

df_substratedata = pd.DataFrame(data)
df_substratedata

,substrate1,substrate2,substrate3
0,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin

In [ ]:
df_enzymedata["key"] = 1
df_substratedata["key"] = 1


result = pd.merge(df_enzymedata, df_substratedata, on="key", how="outer")
result.drop(columns="key", inplace=True)

In [5]:
result

,enzyme,Sequence,substrate1,substrate2,substrate3
0,Droo_175168,VLLALPVILILLYLKQKSSGKRRRQPPGPSGLPFIGNLHQFDGIYP...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
1,Dcom_195433,MRANTAEKWITERAKRYGPVSKLSLFGNATVFIYGQSANKFLFADN...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
2,Dcom_249831,MTLKFGMINIVVASSTEMAKEILQKKDQTFLGRPVPDAIRGEKGYE...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
3,Dcom_272966,MGLPFFGEMLAFLWYFKVIRRPDDYINVKRRKYGDGEGLYRTHLFG...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
4,Dcom_061020,MTHVTLSNLAKIHGPVMSFKLGTQLLIVGSSSAAAEEILKTNDRIL...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
...,...,...,...,...,...
290,Droo_046339,MAHAVSSCVSYSHLLVNRQNELPSSRSPSSPVTHFSNCKRKGFSVR...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
291,Dcom_143281,MASASSWLHKSFHDSLLCFFILSLTIMFLILFIFHLLRVRIWCNCE...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
292,Droo_148538,MPNYQFMALISHFTTTPPPPTHDPFMSYSYFSNYLHSIIMASPNHS...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
293,Droo_006827,MASSLSLLQLSPQILQTRGQRNRLSNVKSNGTGRDARRFRCSSSLN...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin
294,Dcom_165338,MSWWWAGAIGAAKKKLEEDDAPPKHSSVALIVGVTGIIGNSLAEIL...,3β-hydroxy-5β-pregnane-20-one,"5β-pregnane-3β,14β-diol-20-one",digitoxigenin